n = input('Digite algo: ')
print ('É alfabética:?',n.isalpha())
print ('É um número?: ',n.isnumeric())
print ('É alfanumérico?:',n.isalnum())
print ('Está maiúsculo?: ',n.isupper())
print('Está minúsculo?: ',n.islower())
print('Está capitalizado?: ',n.istitle())